networks:
  netstack-core:
    external: true

services:
  # gNodeB 1 - eMBB 專用
  gnb1:
    image: gradiant/ueransim:3.2.6
    container_name: netstack-gnb1
    volumes:
      - ../config/gnb1.yaml:/opt/ueransim/config/gnb.yaml
    command: nr-gnb -c /opt/ueransim/config/gnb.yaml
    cap_add:
      - all
    privileged: true
    depends_on:
      - amf
    networks:
      netstack-core:
        ipv4_address: 172.20.1.10
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pgrep", "nr-gnb"]
      interval: 10s
      timeout: 5s
      retries: 3

  # gNodeB 2 - uRLLC 專用  
  gnb2:
    image: gradiant/ueransim:3.2.6
    container_name: netstack-gnb2
    volumes:
      - ../config/gnb2.yaml:/opt/ueransim/config/gnb.yaml
    command: nr-gnb -c /opt/ueransim/config/gnb.yaml
    cap_add:
      - all
    privileged: true
    depends_on:
      - amf
    networks:
      netstack-core:
        ipv4_address: 172.20.1.20
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pgrep", "nr-gnb"]
      interval: 10s
      timeout: 5s
      retries: 3

  # UE 群組 1 - eMBB Slice 用戶
  ues1:
    image: gradiant/ueransim:3.2.6
    container_name: netstack-ues1
    volumes:
      - ../config/ue1.yaml:/opt/ueransim/config/ue1.yaml
      - ../config/ue2.yaml:/opt/ueransim/config/ue2.yaml
      - ../config/ue3.yaml:/opt/ueransim/config/ue3.yaml
    command: |
      sh -c "
        nr-ue -c /opt/ueransim/config/ue1.yaml &
        nr-ue -c /opt/ueransim/config/ue2.yaml &
        nr-ue -c /opt/ueransim/config/ue3.yaml &
        wait
      "
    cap_add:
      - all
    privileged: true
    depends_on:
      - gnb1
    networks:
      netstack-core:
        ipv4_address: 172.20.1.30
    restart: unless-stopped
    stdin_open: true
    tty: true

  # UE 群組 2 - uRLLC Slice 用戶
  ues2:
    image: gradiant/ueransim:3.2.6
    container_name: netstack-ues2
    volumes:
      - ../config/ue11.yaml:/opt/ueransim/config/ue11.yaml
      - ../config/ue12.yaml:/opt/ueransim/config/ue12.yaml
      - ../config/ue13.yaml:/opt/ueransim/config/ue13.yaml
    command: |
      sh -c "
        nr-ue -c /opt/ueransim/config/ue11.yaml &
        nr-ue -c /opt/ueransim/config/ue12.yaml &
        nr-ue -c /opt/ueransim/config/ue13.yaml &
        wait
      "
    cap_add:
      - all
    privileged: true
    depends_on:
      - gnb2
    networks:
      netstack-core:
        ipv4_address: 172.20.1.40
    restart: unless-stopped
    stdin_open: true
    tty: true

  # UE 群組 3 - mMTC Slice 用戶
  ues3:
    image: gradiant/ueransim:3.2.6
    container_name: netstack-ues3
    volumes:
      - ../config/ue21.yaml:/opt/ueransim/config/ue21.yaml
      - ../config/ue22.yaml:/opt/ueransim/config/ue22.yaml
    command: |
      sh -c "
        nr-ue -c /opt/ueransim/config/ue21.yaml &
        nr-ue -c /opt/ueransim/config/ue22.yaml &
        wait
      "
    cap_add:
      - all
    privileged: true
    depends_on:
      - gnb1
      - gnb2
    networks:
      netstack-core:
        ipv4_address: 172.20.1.45
    restart: unless-stopped
    stdin_open: true
    tty: true

  # 測試用 UE (可動態切換 Slice)
  ue-test:
    image: gradiant/ueransim:3.2.6
    container_name: netstack-ue-test
    volumes:
      - ../config/ue-test.yaml:/opt/ueransim/config/ue.yaml
    command: nr-ue -c /opt/ueransim/config/ue.yaml
    cap_add:
      - all
    privileged: true
    depends_on:
      - gnb1
      - gnb2
    networks:
      netstack-core:
        ipv4_address: 172.20.1.50
    restart: unless-stopped
    stdin_open: true
    tty: true

  # 網路效能測試工具
  network-tester:
    image: alpine:latest
    container_name: netstack-network-tester
    command: |
      sh -c "
        apk add --no-cache curl iproute2 iputils tcpdump iperf3 &&
        while true; do sleep 3600; done
      "
    cap_add:
      - NET_ADMIN
    networks:
      netstack-core:
        ipv4_address: 172.20.1.100
    restart: unless-stopped
    stdin_open: true
    tty: true 